/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const WithdrawalRequest = IDL.Record({
  'processed' : IDL.Bool,
  'amount' : IDL.Nat,
  'requestTime' : Time,
});
export const Bet = IDL.Record({
  'betAmount' : IDL.Nat,
  'betTime' : Time,
  'betColor' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'coins' : IDL.Nat,
  'withdrawalRequests' : IDL.Vec(WithdrawalRequest),
  'lastBonusTime' : Time,
  'dailyStreak' : IDL.Nat,
  'betHistory' : IDL.Vec(Bet),
  'lastSpinTime' : Time,
});
export const GamePhase = IDL.Variant({
  'reveal' : IDL.Record({ 'startTime' : Time, 'result' : IDL.Opt(IDL.Text) }),
  'betting' : IDL.Record({ 'startTime' : Time }),
  'cooldown' : IDL.Record({ 'startTime' : Time }),
});
export const RoundView = IDL.Record({
  'startTime' : Time,
  'result' : IDL.Opt(IDL.Text),
  'bets' : IDL.Vec(IDL.Tuple(IDL.Principal, Bet)),
  'totalRedBets' : IDL.Nat,
  'totalGreenBets' : IDL.Nat,
  'roundId' : IDL.Nat,
  'totalVioletBets' : IDL.Nat,
  'phase' : GamePhase,
});
export const MultiplierConfig = IDL.Record({
  'red' : IDL.Float64,
  'green' : IDL.Float64,
  'violet' : IDL.Float64,
});
export const DepositRequest = IDL.Record({
  'user' : IDL.Principal,
  'amount' : IDL.Nat,
  'bonusAmount' : IDL.Nat,
  'requestTime' : Time,
  'approved' : IDL.Bool,
  'index' : IDL.Nat,
});
export const PaymentMethod = IDL.Record({
  'upiId' : IDL.Text,
  'qrImageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyBonus' : IDL.Func([], [], []),
  'clearManualOverride' : IDL.Func([], [], []),
  'depositCoins' : IDL.Func([IDL.Nat], [], []),
  'getAdminLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllUserHoldings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRoundBets' : IDL.Func(
      [],
      [IDL.Record({ 'red' : IDL.Nat, 'green' : IDL.Nat, 'violet' : IDL.Nat })],
      ['query'],
    ),
  'getCurrentRoundPhase' : IDL.Func([], [IDL.Text], ['query']),
  'getGameState' : IDL.Func(
      [],
      [
        IDL.Record({
          'roundHistory' : IDL.Vec(RoundView),
          'autoResolve' : IDL.Bool,
          'manualResult' : IDL.Opt(IDL.Text),
          'currentRoundId' : IDL.Nat,
          'phase' : IDL.Text,
          'multipliers' : MultiplierConfig,
          'phaseStartTimestamp' : Time,
        }),
      ],
      ['query'],
    ),
  'getPaymentMethod' : IDL.Func([], [PaymentMethod], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasFirstDepositBonus' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWithdrawalProcessed' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setManualResultOverride' : IDL.Func([IDL.Text], [], []),
  'setMultipliers' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Float64], [], []),
  'setPaymentMethod' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'spinWheel' : IDL.Func([], [IDL.Nat], []),
  'toggleAutoResolve' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const WithdrawalRequest = IDL.Record({
    'processed' : IDL.Bool,
    'amount' : IDL.Nat,
    'requestTime' : Time,
  });
  const Bet = IDL.Record({
    'betAmount' : IDL.Nat,
    'betTime' : Time,
    'betColor' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'coins' : IDL.Nat,
    'withdrawalRequests' : IDL.Vec(WithdrawalRequest),
    'lastBonusTime' : Time,
    'dailyStreak' : IDL.Nat,
    'betHistory' : IDL.Vec(Bet),
    'lastSpinTime' : Time,
  });
  const GamePhase = IDL.Variant({
    'reveal' : IDL.Record({ 'startTime' : Time, 'result' : IDL.Opt(IDL.Text) }),
    'betting' : IDL.Record({ 'startTime' : Time }),
    'cooldown' : IDL.Record({ 'startTime' : Time }),
  });
  const RoundView = IDL.Record({
    'startTime' : Time,
    'result' : IDL.Opt(IDL.Text),
    'bets' : IDL.Vec(IDL.Tuple(IDL.Principal, Bet)),
    'totalRedBets' : IDL.Nat,
    'totalGreenBets' : IDL.Nat,
    'roundId' : IDL.Nat,
    'totalVioletBets' : IDL.Nat,
    'phase' : GamePhase,
  });
  const MultiplierConfig = IDL.Record({
    'red' : IDL.Float64,
    'green' : IDL.Float64,
    'violet' : IDL.Float64,
  });
  const DepositRequest = IDL.Record({
    'user' : IDL.Principal,
    'amount' : IDL.Nat,
    'bonusAmount' : IDL.Nat,
    'requestTime' : Time,
    'approved' : IDL.Bool,
    'index' : IDL.Nat,
  });
  const PaymentMethod = IDL.Record({
    'upiId' : IDL.Text,
    'qrImageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyBonus' : IDL.Func([], [], []),
    'clearManualOverride' : IDL.Func([], [], []),
    'depositCoins' : IDL.Func([IDL.Nat], [], []),
    'getAdminLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getAllUserHoldings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRoundBets' : IDL.Func(
        [],
        [
          IDL.Record({
            'red' : IDL.Nat,
            'green' : IDL.Nat,
            'violet' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCurrentRoundPhase' : IDL.Func([], [IDL.Text], ['query']),
    'getGameState' : IDL.Func(
        [],
        [
          IDL.Record({
            'roundHistory' : IDL.Vec(RoundView),
            'autoResolve' : IDL.Bool,
            'manualResult' : IDL.Opt(IDL.Text),
            'currentRoundId' : IDL.Nat,
            'phase' : IDL.Text,
            'multipliers' : MultiplierConfig,
            'phaseStartTimestamp' : Time,
          }),
        ],
        ['query'],
      ),
    'getPaymentMethod' : IDL.Func([], [PaymentMethod], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasFirstDepositBonus' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWithdrawalProcessed' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setManualResultOverride' : IDL.Func([IDL.Text], [], []),
    'setMultipliers' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setPaymentMethod' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'spinWheel' : IDL.Func([], [IDL.Nat], []),
    'toggleAutoResolve' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
