/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DepositRequest = IDL.Record({
  'bonusAmount' : IDL.Nat,
  'user' : IDL.Principal,
  'approved' : IDL.Bool,
  'index' : IDL.Nat,
  'amount' : IDL.Nat,
  'requestTime' : Time,
});
export const WithdrawalRequest = IDL.Record({
  'processed' : IDL.Bool,
  'amount' : IDL.Nat,
  'requestTime' : Time,
});
export const Bet = IDL.Record({
  'betAmount' : IDL.Nat,
  'betTime' : Time,
  'betColor' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'coins' : IDL.Nat,
  'withdrawalRequests' : IDL.Vec(WithdrawalRequest),
  'lastBonusTime' : Time,
  'dailyStreak' : IDL.Nat,
  'lastSpinTime' : Time,
  'betHistory' : IDL.Vec(Bet),
});
export const GamePhase = IDL.Variant({
  'reveal' : IDL.Record({ 'startTime' : Time, 'result' : IDL.Opt(IDL.Text) }),
  'betting' : IDL.Record({ 'startTime' : Time }),
  'cooldown' : IDL.Record({ 'startTime' : Time }),
});
export const RoundView = IDL.Record({
  'startTime' : Time,
  'result' : IDL.Opt(IDL.Text),
  'bets' : IDL.Vec(IDL.Tuple(IDL.Principal, Bet)),
  'totalRedBets' : IDL.Nat,
  'totalGreenBets' : IDL.Nat,
  'roundId' : IDL.Nat,
  'totalVioletBets' : IDL.Nat,
  'phase' : GamePhase,
});
export const MultiplierConfig = IDL.Record({
  'red' : IDL.Float64,
  'green' : IDL.Float64,
  'violet' : IDL.Float64,
});
export const PaymentMethod = IDL.Record({
  'qrImageUrl' : IDL.Text,
  'upiId' : IDL.Text,
});
export const TransactionLog = IDL.Record({
  'userId' : IDL.Principal,
  'logType' : IDL.Text,
  'timestamp' : Time,
  'adminId' : IDL.Principal,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'assignAdminRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCoinsToAdmin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'claimDailyBonus' : IDL.Func([], [], []),
  'clearForcedResult' : IDL.Func([], [], []),
  'clearManualOverride' : IDL.Func([], [], []),
  'depositCoins' : IDL.Func([IDL.Nat], [], []),
  'forceResult' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAdminBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getAdminLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllUserHoldings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
      ['query'],
    ),
  'getCallerAdminRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerApprovedDepositTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCurrentRoundBets' : IDL.Func(
      [],
      [IDL.Record({ 'red' : IDL.Nat, 'green' : IDL.Nat, 'violet' : IDL.Nat })],
      ['query'],
    ),
  'getCurrentRoundPhase' : IDL.Func([], [IDL.Text], ['query']),
  'getForceResultStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'forcedColor' : IDL.Opt(IDL.Text),
          'isActive' : IDL.Bool,
          'forcedSize' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getGameState' : IDL.Func(
      [],
      [
        IDL.Record({
          'forcedColor' : IDL.Opt(IDL.Text),
          'roundHistory' : IDL.Vec(RoundView),
          'autoResolve' : IDL.Bool,
          'manualResult' : IDL.Opt(IDL.Text),
          'currentRoundId' : IDL.Nat,
          'phase' : IDL.Text,
          'forcedSize' : IDL.Opt(IDL.Text),
          'multipliers' : MultiplierConfig,
          'phaseStartTimestamp' : Time,
        }),
      ],
      ['query'],
    ),
  'getMyAdminBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaymentMethod' : IDL.Func([], [PaymentMethod], ['query']),
  'getSuperAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getTransactionLogs' : IDL.Func([], [IDL.Vec(TransactionLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasApprovedDeposit' : IDL.Func([], [IDL.Bool], ['query']),
  'hasFirstDepositBonus' : IDL.Func([], [IDL.Bool], ['query']),
  'markWithdrawalProcessed' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setManualResultOverride' : IDL.Func([IDL.Text], [], []),
  'setMultipliers' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Float64], [], []),
  'setPaymentMethod' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setSuperAdmin' : IDL.Func([IDL.Principal], [], []),
  'setUserCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'spinWheel' : IDL.Func([], [IDL.Nat], []),
  'submitDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'toggleAutoResolve' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DepositRequest = IDL.Record({
    'bonusAmount' : IDL.Nat,
    'user' : IDL.Principal,
    'approved' : IDL.Bool,
    'index' : IDL.Nat,
    'amount' : IDL.Nat,
    'requestTime' : Time,
  });
  const WithdrawalRequest = IDL.Record({
    'processed' : IDL.Bool,
    'amount' : IDL.Nat,
    'requestTime' : Time,
  });
  const Bet = IDL.Record({
    'betAmount' : IDL.Nat,
    'betTime' : Time,
    'betColor' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'coins' : IDL.Nat,
    'withdrawalRequests' : IDL.Vec(WithdrawalRequest),
    'lastBonusTime' : Time,
    'dailyStreak' : IDL.Nat,
    'lastSpinTime' : Time,
    'betHistory' : IDL.Vec(Bet),
  });
  const GamePhase = IDL.Variant({
    'reveal' : IDL.Record({ 'startTime' : Time, 'result' : IDL.Opt(IDL.Text) }),
    'betting' : IDL.Record({ 'startTime' : Time }),
    'cooldown' : IDL.Record({ 'startTime' : Time }),
  });
  const RoundView = IDL.Record({
    'startTime' : Time,
    'result' : IDL.Opt(IDL.Text),
    'bets' : IDL.Vec(IDL.Tuple(IDL.Principal, Bet)),
    'totalRedBets' : IDL.Nat,
    'totalGreenBets' : IDL.Nat,
    'roundId' : IDL.Nat,
    'totalVioletBets' : IDL.Nat,
    'phase' : GamePhase,
  });
  const MultiplierConfig = IDL.Record({
    'red' : IDL.Float64,
    'green' : IDL.Float64,
    'violet' : IDL.Float64,
  });
  const PaymentMethod = IDL.Record({
    'qrImageUrl' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const TransactionLog = IDL.Record({
    'userId' : IDL.Principal,
    'logType' : IDL.Text,
    'timestamp' : Time,
    'adminId' : IDL.Principal,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'assignAdminRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCoinsToAdmin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'claimDailyBonus' : IDL.Func([], [], []),
    'clearForcedResult' : IDL.Func([], [], []),
    'clearManualOverride' : IDL.Func([], [], []),
    'depositCoins' : IDL.Func([IDL.Nat], [], []),
    'forceResult' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAdminBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getAdminLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getAllUserHoldings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
        ['query'],
      ),
    'getCallerAdminRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerApprovedDepositTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCurrentRoundBets' : IDL.Func(
        [],
        [
          IDL.Record({
            'red' : IDL.Nat,
            'green' : IDL.Nat,
            'violet' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCurrentRoundPhase' : IDL.Func([], [IDL.Text], ['query']),
    'getForceResultStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'forcedColor' : IDL.Opt(IDL.Text),
            'isActive' : IDL.Bool,
            'forcedSize' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getGameState' : IDL.Func(
        [],
        [
          IDL.Record({
            'forcedColor' : IDL.Opt(IDL.Text),
            'roundHistory' : IDL.Vec(RoundView),
            'autoResolve' : IDL.Bool,
            'manualResult' : IDL.Opt(IDL.Text),
            'currentRoundId' : IDL.Nat,
            'phase' : IDL.Text,
            'forcedSize' : IDL.Opt(IDL.Text),
            'multipliers' : MultiplierConfig,
            'phaseStartTimestamp' : Time,
          }),
        ],
        ['query'],
      ),
    'getMyAdminBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentMethod' : IDL.Func([], [PaymentMethod], ['query']),
    'getSuperAdminPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getTransactionLogs' : IDL.Func([], [IDL.Vec(TransactionLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasApprovedDeposit' : IDL.Func([], [IDL.Bool], ['query']),
    'hasFirstDepositBonus' : IDL.Func([], [IDL.Bool], ['query']),
    'markWithdrawalProcessed' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setManualResultOverride' : IDL.Func([IDL.Text], [], []),
    'setMultipliers' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setPaymentMethod' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setSuperAdmin' : IDL.Func([IDL.Principal], [], []),
    'setUserCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'spinWheel' : IDL.Func([], [IDL.Nat], []),
    'submitDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'toggleAutoResolve' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };