/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'betAmount' : bigint,
  'betTime' : Time,
  'betColor' : string,
}
export interface DepositRequest {
  'bonusAmount' : bigint,
  'user' : Principal,
  'approved' : boolean,
  'index' : bigint,
  'amount' : bigint,
  'requestTime' : Time,
}
export type GamePhase = {
    'reveal' : { 'startTime' : Time, 'result' : [] | [string] }
  } |
  { 'betting' : { 'startTime' : Time } } |
  { 'cooldown' : { 'startTime' : Time } };
export interface MultiplierConfig {
  'red' : number,
  'green' : number,
  'violet' : number,
}
export interface PaymentMethod { 'qrImageUrl' : string, 'upiId' : string }
export interface RoundView {
  'startTime' : Time,
  'result' : [] | [string],
  'bets' : Array<[Principal, Bet]>,
  'totalRedBets' : bigint,
  'totalGreenBets' : bigint,
  'roundId' : bigint,
  'totalVioletBets' : bigint,
  'phase' : GamePhase,
}
export type Time = bigint;
export interface TransactionLog {
  'userId' : Principal,
  'logType' : string,
  'timestamp' : Time,
  'adminId' : Principal,
  'amount' : bigint,
}
export interface UserProfile {
  'coins' : bigint,
  'withdrawalRequests' : Array<WithdrawalRequest>,
  'lastBonusTime' : Time,
  'dailyStreak' : bigint,
  'lastSpinTime' : Time,
  'betHistory' : Array<Bet>,
}
export interface WithdrawalRequest {
  'processed' : boolean,
  'amount' : bigint,
  'requestTime' : Time,
}
export interface _SERVICE {
  'adjustUserCoins' : ActorMethod<[Principal, bigint], undefined>,
  'approveDeposit' : ActorMethod<[bigint], undefined>,
  'assignAdminRole' : ActorMethod<[Principal, string], undefined>,
  'assignCoinsToAdmin' : ActorMethod<[Principal, bigint], undefined>,
  'claimDailyBonus' : ActorMethod<[], undefined>,
  'clearForcedResult' : ActorMethod<[], undefined>,
  'clearManualOverride' : ActorMethod<[], undefined>,
  'depositCoins' : ActorMethod<[bigint], undefined>,
  'forceResult' : ActorMethod<[string, string], undefined>,
  'getAdminBalance' : ActorMethod<[Principal], bigint>,
  'getAdminLogs' : ActorMethod<[], Array<string>>,
  'getAllDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getAllUserHoldings' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAllWithdrawalRequests' : ActorMethod<
    [],
    Array<[Principal, WithdrawalRequest]>
  >,
  'getCallerAdminRole' : ActorMethod<[], string>,
  'getCallerApprovedDepositTotal' : ActorMethod<[], bigint>,
  'getCallerDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCurrentRoundBets' : ActorMethod<
    [],
    { 'red' : bigint, 'green' : bigint, 'violet' : bigint }
  >,
  'getCurrentRoundPhase' : ActorMethod<[], string>,
  'getForceResultStatus' : ActorMethod<
    [],
    {
      'forcedColor' : [] | [string],
      'isActive' : boolean,
      'forcedSize' : [] | [string],
    }
  >,
  'getGameState' : ActorMethod<
    [],
    {
      'forcedColor' : [] | [string],
      'roundHistory' : Array<RoundView>,
      'autoResolve' : boolean,
      'manualResult' : [] | [string],
      'currentRoundId' : bigint,
      'phase' : string,
      'forcedSize' : [] | [string],
      'multipliers' : MultiplierConfig,
      'phaseStartTimestamp' : Time,
    }
  >,
  'getMyAdminBalance' : ActorMethod<[], bigint>,
  'getPaymentMethod' : ActorMethod<[], PaymentMethod>,
  'getSuperAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getTransactionLogs' : ActorMethod<[], Array<TransactionLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasApprovedDeposit' : ActorMethod<[], boolean>,
  'hasFirstDepositBonus' : ActorMethod<[], boolean>,
  'markWithdrawalProcessed' : ActorMethod<[Principal, bigint], undefined>,
  'placeBet' : ActorMethod<[string, bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setManualResultOverride' : ActorMethod<[string], undefined>,
  'setMultipliers' : ActorMethod<[number, number, number], undefined>,
  'setPaymentMethod' : ActorMethod<[string, string], undefined>,
  'setSuperAdmin' : ActorMethod<[Principal], undefined>,
  'setUserCoins' : ActorMethod<[Principal, bigint], undefined>,
  'spinWheel' : ActorMethod<[], bigint>,
  'submitDepositRequest' : ActorMethod<[bigint], undefined>,
  'toggleAutoResolve' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];