/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'betAmount' : bigint,
  'betTime' : Time,
  'betColor' : string,
}
export type GamePhase = {
    'reveal' : { 'startTime' : Time, 'result' : [] | [string] }
  } |
  { 'betting' : { 'startTime' : Time } } |
  { 'cooldown' : { 'startTime' : Time } };
export interface MultiplierConfig {
  'red' : number,
  'green' : number,
  'violet' : number,
}
export interface RoundView {
  'startTime' : Time,
  'result' : [] | [string],
  'bets' : Array<[Principal, Bet]>,
  'totalRedBets' : bigint,
  'totalGreenBets' : bigint,
  'roundId' : bigint,
  'totalVioletBets' : bigint,
  'phase' : GamePhase,
}
export type Time = bigint;
export interface UserProfile {
  'coins' : bigint,
  'withdrawalRequests' : Array<WithdrawalRequest>,
  'lastBonusTime' : Time,
  'dailyStreak' : bigint,
  'betHistory' : Array<Bet>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'processed' : boolean,
  'amount' : bigint,
  'requestTime' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustUserCoins' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyBonus' : ActorMethod<[], undefined>,
  'clearManualOverride' : ActorMethod<[], undefined>,
  'depositCoins' : ActorMethod<[bigint], undefined>,
  'getAdminLogs' : ActorMethod<[], Array<string>>,
  'getAllUserHoldings' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAllWithdrawalRequests' : ActorMethod<
    [],
    Array<[Principal, WithdrawalRequest]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRoundBets' : ActorMethod<
    [],
    { 'red' : bigint, 'green' : bigint, 'violet' : bigint }
  >,
  'getCurrentRoundPhase' : ActorMethod<[], string>,
  'getGameState' : ActorMethod<
    [],
    {
      'roundHistory' : Array<RoundView>,
      'autoResolve' : boolean,
      'manualResult' : [] | [string],
      'currentRoundId' : bigint,
      'phase' : string,
      'multipliers' : MultiplierConfig,
      'phaseStartTimestamp' : Time,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markWithdrawalProcessed' : ActorMethod<[Principal, bigint], undefined>,
  'placeBet' : ActorMethod<[string, bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setManualResultOverride' : ActorMethod<[string], undefined>,
  'setMultipliers' : ActorMethod<[number, number, number], undefined>,
  'toggleAutoResolve' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];