/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RoundView {
    startTime: Time;
    result?: string;
    bets: Array<[Principal, Bet]>;
    totalRedBets: bigint;
    totalGreenBets: bigint;
    roundId: bigint;
    totalVioletBets: bigint;
    phase: GamePhase;
}
export interface PaymentMethod {
    qrImageUrl: string;
    upiId: string;
}
export interface TransactionLog {
    userId: Principal;
    logType: string;
    timestamp: Time;
    adminId: Principal;
    amount: bigint;
}
export type GamePhase = {
    __kind__: "reveal";
    reveal: {
        startTime: Time;
        result?: string;
    };
} | {
    __kind__: "betting";
    betting: {
        startTime: Time;
    };
} | {
    __kind__: "cooldown";
    cooldown: {
        startTime: Time;
    };
};
export interface DepositRequest {
    bonusAmount: bigint;
    user: Principal;
    approved: boolean;
    index: bigint;
    amount: bigint;
    requestTime: Time;
}
export interface Bet {
    betAmount: bigint;
    betTime: Time;
    betColor: string;
}
export interface WithdrawalRequest {
    processed: boolean;
    amount: bigint;
    requestTime: Time;
}
export interface MultiplierConfig {
    red: number;
    green: number;
    violet: number;
}
export interface UserProfile {
    coins: bigint;
    withdrawalRequests: Array<WithdrawalRequest>;
    lastBonusTime: Time;
    dailyStreak: bigint;
    lastSpinTime: Time;
    betHistory: Array<Bet>;
}
export interface backendInterface {
    adjustUserCoins(user: Principal, amount: bigint): Promise<void>;
    approveDeposit(requestIndex: bigint): Promise<void>;
    assignAdminRole(user: Principal, role: string): Promise<void>;
    assignCoinsToAdmin(admin: Principal, amount: bigint): Promise<void>;
    claimDailyBonus(): Promise<void>;
    clearForcedResult(): Promise<void>;
    clearManualOverride(): Promise<void>;
    depositCoins(amount: bigint): Promise<void>;
    forceResult(color: string, size: string): Promise<void>;
    getAdminBalance(admin: Principal): Promise<bigint>;
    getAdminLogs(): Promise<Array<string>>;
    getAllDepositRequests(): Promise<Array<DepositRequest>>;
    getAllUserHoldings(): Promise<Array<[Principal, bigint]>>;
    getAllWithdrawalRequests(): Promise<Array<[Principal, WithdrawalRequest]>>;
    getCallerAdminRole(): Promise<string>;
    getCallerApprovedDepositTotal(): Promise<bigint>;
    getCallerDepositRequests(): Promise<Array<DepositRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCurrentRoundBets(): Promise<{
        red: bigint;
        green: bigint;
        violet: bigint;
    }>;
    getCurrentRoundPhase(): Promise<string>;
    getForceResultStatus(): Promise<{
        forcedColor?: string;
        isActive: boolean;
        forcedSize?: string;
    }>;
    getGameState(): Promise<{
        forcedColor?: string;
        roundHistory: Array<RoundView>;
        autoResolve: boolean;
        manualResult?: string;
        currentRoundId: bigint;
        phase: string;
        forcedSize?: string;
        multipliers: MultiplierConfig;
        phaseStartTimestamp: Time;
    }>;
    getMyAdminBalance(): Promise<bigint>;
    getPaymentMethod(): Promise<PaymentMethod>;
    getSuperAdminPrincipal(): Promise<Principal | null>;
    getTransactionLogs(): Promise<Array<TransactionLog>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasApprovedDeposit(): Promise<boolean>;
    hasFirstDepositBonus(): Promise<boolean>;
    markWithdrawalProcessed(user: Principal, index: bigint): Promise<void>;
    placeBet(color: string, amount: bigint): Promise<void>;
    requestWithdrawal(amount: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setManualResultOverride(result: string): Promise<void>;
    setMultipliers(red: number, green: number, violet: number): Promise<void>;
    setPaymentMethod(upiId: string, qrImageUrl: string): Promise<void>;
    setSuperAdmin(newSuperAdmin: Principal): Promise<void>;
    setUserCoins(user: Principal, amount: bigint): Promise<void>;
    spinWheel(): Promise<bigint>;
    submitDepositRequest(amount: bigint): Promise<void>;
    toggleAutoResolve(): Promise<void>;
}
import type { Bet as _Bet, GamePhase as _GamePhase, MultiplierConfig as _MultiplierConfig, RoundView as _RoundView, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adjustUserCoins(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserCoins(arg0, arg1);
            return result;
        }
    }
    async approveDeposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0);
            return result;
        }
    }
    async assignAdminRole(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdminRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdminRole(arg0, arg1);
            return result;
        }
    }
    async assignCoinsToAdmin(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCoinsToAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCoinsToAdmin(arg0, arg1);
            return result;
        }
    }
    async claimDailyBonus(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyBonus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyBonus();
            return result;
        }
    }
    async clearForcedResult(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearForcedResult();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearForcedResult();
            return result;
        }
    }
    async clearManualOverride(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearManualOverride();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearManualOverride();
            return result;
        }
    }
    async depositCoins(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositCoins(arg0);
            return result;
        }
    }
    async forceResult(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.forceResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceResult(arg0, arg1);
            return result;
        }
    }
    async getAdminBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminBalance(arg0);
            return result;
        }
    }
    async getAdminLogs(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminLogs();
            return result;
        }
    }
    async getAllDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepositRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepositRequests();
            return result;
        }
    }
    async getAllUserHoldings(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserHoldings();
            return result;
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<[Principal, WithdrawalRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return result;
        }
    }
    async getCallerAdminRole(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAdminRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAdminRole();
            return result;
        }
    }
    async getCallerApprovedDepositTotal(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerApprovedDepositTotal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerApprovedDepositTotal();
            return result;
        }
    }
    async getCallerDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDepositRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDepositRequests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWithdrawalRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWithdrawalRequests();
            return result;
        }
    }
    async getCurrentRoundBets(): Promise<{
        red: bigint;
        green: bigint;
        violet: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRoundBets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRoundBets();
            return result;
        }
    }
    async getCurrentRoundPhase(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRoundPhase();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRoundPhase();
            return result;
        }
    }
    async getForceResultStatus(): Promise<{
        forcedColor?: string;
        isActive: boolean;
        forcedSize?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getForceResultStatus();
                return from_candid_record_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForceResultStatus();
            return from_candid_record_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(): Promise<{
        forcedColor?: string;
        roundHistory: Array<RoundView>;
        autoResolve: boolean;
        manualResult?: string;
        currentRoundId: bigint;
        phase: string;
        forcedSize?: string;
        multipliers: MultiplierConfig;
        phaseStartTimestamp: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState();
                return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState();
            return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAdminBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAdminBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAdminBalance();
            return result;
        }
    }
    async getPaymentMethod(): Promise<PaymentMethod> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethod();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethod();
            return result;
        }
    }
    async getSuperAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuperAdminPrincipal();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuperAdminPrincipal();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionLogs(): Promise<Array<TransactionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionLogs();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasApprovedDeposit(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasApprovedDeposit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasApprovedDeposit();
            return result;
        }
    }
    async hasFirstDepositBonus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasFirstDepositBonus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasFirstDepositBonus();
            return result;
        }
    }
    async markWithdrawalProcessed(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWithdrawalProcessed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWithdrawalProcessed(arg0, arg1);
            return result;
        }
    }
    async placeBet(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, arg1);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setManualResultOverride(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualResultOverride(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualResultOverride(arg0);
            return result;
        }
    }
    async setMultipliers(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMultipliers(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMultipliers(arg0, arg1, arg2);
            return result;
        }
    }
    async setPaymentMethod(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentMethod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentMethod(arg0, arg1);
            return result;
        }
    }
    async setSuperAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSuperAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSuperAdmin(arg0);
            return result;
        }
    }
    async setUserCoins(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserCoins(arg0, arg1);
            return result;
        }
    }
    async spinWheel(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.spinWheel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spinWheel();
            return result;
        }
    }
    async submitDepositRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositRequest(arg0);
            return result;
        }
    }
    async toggleAutoResolve(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAutoResolve();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAutoResolve();
            return result;
        }
    }
}
function from_candid_GamePhase_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RoundView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoundView): RoundView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Time;
    result: [] | [string];
}): {
    startTime: Time;
    result?: string;
} {
    return {
        startTime: value.startTime,
        result: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.result))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forcedColor: [] | [string];
    isActive: boolean;
    forcedSize: [] | [string];
}): {
    forcedColor?: string;
    isActive: boolean;
    forcedSize?: string;
} {
    return {
        forcedColor: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.forcedColor)),
        isActive: value.isActive,
        forcedSize: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.forcedSize))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forcedColor: [] | [string];
    roundHistory: Array<_RoundView>;
    autoResolve: boolean;
    manualResult: [] | [string];
    currentRoundId: bigint;
    phase: string;
    forcedSize: [] | [string];
    multipliers: _MultiplierConfig;
    phaseStartTimestamp: _Time;
}): {
    forcedColor?: string;
    roundHistory: Array<RoundView>;
    autoResolve: boolean;
    manualResult?: string;
    currentRoundId: bigint;
    phase: string;
    forcedSize?: string;
    multipliers: MultiplierConfig;
    phaseStartTimestamp: Time;
} {
    return {
        forcedColor: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.forcedColor)),
        roundHistory: from_candid_vec_n5(_uploadFile, _downloadFile, value.roundHistory),
        autoResolve: value.autoResolve,
        manualResult: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.manualResult)),
        currentRoundId: value.currentRoundId,
        phase: value.phase,
        forcedSize: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.forcedSize)),
        multipliers: value.multipliers,
        phaseStartTimestamp: value.phaseStartTimestamp
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Time;
    result: [] | [string];
    bets: Array<[Principal, _Bet]>;
    totalRedBets: bigint;
    totalGreenBets: bigint;
    roundId: bigint;
    totalVioletBets: bigint;
    phase: _GamePhase;
}): {
    startTime: Time;
    result?: string;
    bets: Array<[Principal, Bet]>;
    totalRedBets: bigint;
    totalGreenBets: bigint;
    roundId: bigint;
    totalVioletBets: bigint;
    phase: GamePhase;
} {
    return {
        startTime: value.startTime,
        result: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.result)),
        bets: value.bets,
        totalRedBets: value.totalRedBets,
        totalGreenBets: value.totalGreenBets,
        roundId: value.roundId,
        totalVioletBets: value.totalVioletBets,
        phase: from_candid_GamePhase_n8(_uploadFile, _downloadFile, value.phase)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reveal: {
        startTime: _Time;
        result: [] | [string];
    };
} | {
    betting: {
        startTime: _Time;
    };
} | {
    cooldown: {
        startTime: _Time;
    };
}): {
    __kind__: "reveal";
    reveal: {
        startTime: Time;
        result?: string;
    };
} | {
    __kind__: "betting";
    betting: {
        startTime: Time;
    };
} | {
    __kind__: "cooldown";
    cooldown: {
        startTime: Time;
    };
} {
    return "reveal" in value ? {
        __kind__: "reveal",
        reveal: from_candid_record_n10(_uploadFile, _downloadFile, value.reveal)
    } : "betting" in value ? {
        __kind__: "betting",
        betting: value.betting
    } : "cooldown" in value ? {
        __kind__: "cooldown",
        cooldown: value.cooldown
    } : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoundView>): Array<RoundView> {
    return value.map((x)=>from_candid_RoundView_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
